### ISSUE TITLE
Inventory classification 

### ISSUE THREAD

**Issue by Mrsuperx13** [Qelifern/IronFurnaces#52]
**Describe the bug**
I use a mod called inventory tweaks renewed https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed, when I open any iron furnace and use the sort function of that mod it screws up. It moves things out of my toolbar (which it doesn't do in any other inventory), it removes the fuel from furnace etc. I am presuming that's because it's not reading the furnaces' inventory correctly.

**To Reproduce**
1. Have both mods installed
2. open an iron furnace
3. use sort function

**Expected behavior**
Only the player's inventory should be sorted, Players tooldbar and furnace's should not be effected.

**Versions**
- **Iron Furnaces**: 1.16.5-2.6.8
- **Forge**: 36.1.0
- **Fabric**: x.x.x

<details>
  <summary>Crashlog</summary>
  Log goes here
<details>

**Comment by Qelifern** [comment]
Fixed by putting this in the tweaks config:
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockAllthemodiumFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockCopperFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockCrystalFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockDiamondFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockEmeraldFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockGoldFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockIronFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockMillionFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockNetheriteFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockObsidianFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockSilverFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockUnobtainiumFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockVibraniumFurnaceContainer" sortRange = ""
[[sorting.containerOverrides]] containerClass = "ironfurnaces.container.BlockWirelessEnergyHeaterContainer" sortRange = ""
