### ISSUE TITLE
Add a config option to disable XP drops and just void extra XP when at limit.

### ISSUE THREAD

**Issue by jpwanabe** [Qelifern/IronFurnaces#73]
## What should be added or changed?
Config option to disable xp drop entirely

## Why should this be done?
On servers with large player base, a lot of bases have these furnaces running 24/7 If players don't handle it themselves the ammount of XP orbs floating around can get to the point of making the server suffer

**Comment by XenoMustache** [comment]
We are looking into adding features to the mod that allow you to control what the furnace does to the XP. This will include storing it into bottles, voiding it, turning it into fluid xp, etc.

**Comment by TheInfamousAlk** [comment]
I would also like this, even just my base alone generates several tps just from xp orbs. I have so many xp collectors sucking up all the xp that these unobtanium furnaces are producing when the furnaces are at max bandwidth. I have hundreds of thousands of levels stored, and I will approach max java int xp if I don't void it. The furnaces generate SO MUCH xp. And of course the main problem is the lag the xp orbs produce during their short trip from the furnace to the collector.

**Comment by jpwanabe** [comment]
> 

Cover it with lava. That will kill most of them instantly.

**Comment by TheInfamousAlk** [comment]
Oh my god, you're right. I can't believe I didn't think of that. It won't look great but it'll do the job lol.

**Comment by TheInfamousAlk** [comment]
Actually I just realized, the lag itself is coming from the incredible number of xp orbs that appear then are immediately destroyed/despawned with my xp collectors. They don't sit around, gathering on the floor, but there are so many of them constantly appearing and disappearing that it generates a bit of tps time. So lava would do the same or possibly worse since the xp orbs have to "burn" before disappearing. 

So really the only way to prevent this lag and continue using these furnaces is for the xp orbs to never spawn in the world, i.e. either disable xp or in the future allow the furnace to pump the xp out or void it without spawning the orbs in the world.
